//! Vendored, formally-verified fiat-crypto field arithmetic.
//!
//! These submodules are generated by the [fiat-crypto](https://github.com/mit-plv/fiat-crypto)
//! project (see each file's header for exact provenance) and provide branch-free,
//! masked-reduction Montgomery arithmetic plus the Bernstein-Yang `divstep`
//! primitives used for constant-time inversion. They are bridged into
//! `ark_ff::FpConfig` implementations by the `ct_field` module (added later).
//!
//! - [`bn254fq`]: BabyJubJub base field `Fq` (the BN254 scalar prime, 254-bit).
//! - [`bjjfr`]: BabyJubJub scalar field `Fr` (prime-order subgroup order, 251-bit).
//!
//! Regenerate with `scripts/gen_fiat.sh`.

pub mod bjjfr;
pub mod bn254fq;

#[cfg(test)]
mod tests {
    /// Self-consistency checks that exercise the vendored fiat-crypto functions
    /// directly (no arkworks involvement): Montgomery domain round-trips, the
    /// multiplicative identity `mul(one, x) == x`, and `nonzero` semantics.
    macro_rules! self_consistency_tests {
        (
            $modname:ident,
            $field:ident,
            $mont:ident,
            $nonmont:ident,
            $to_mont:ident,
            $from_mont:ident,
            $mul:ident,
            $set_one:ident,
            $nonzero:ident
        ) => {
            mod $modname {
                use crate::backend::fiat::$field::{
                    $from_mont, $mont, $mul, $nonmont, $nonzero, $set_one, $to_mont,
                };

                // Standard-domain (non-Montgomery) test values, all strictly
                // less than the modulus: the top limb is zero and both moduli
                // have a non-zero top limb, so these are valid fiat inputs.
                const SAMPLES: [[u64; 4]; 4] = [
                    [1, 0, 0, 0],
                    [2, 0, 0, 0],
                    [
                        0xdead_beef_0bad_f00d,
                        0x0123_4567_89ab_cdef,
                        0x00ff_00ff_00ff_00ff,
                        0,
                    ],
                    [0xffff_ffff_ffff_ffff, 0xffff_ffff_ffff_ffff, 0xffff, 0],
                ];

                #[test]
                fn montgomery_roundtrip_is_identity() {
                    for a in SAMPLES {
                        let mut mont = $mont([0u64; 4]);
                        $to_mont(&mut mont, &$nonmont(a));
                        let mut back = $nonmont([0u64; 4]);
                        $from_mont(&mut back, &mont);
                        assert_eq!(
                            back.0, a,
                            "to_montgomery ∘ from_montgomery must be identity"
                        );
                    }
                }

                #[test]
                fn mul_by_one_is_identity() {
                    let mut one = $mont([0u64; 4]);
                    $set_one(&mut one);
                    for a in SAMPLES {
                        let mut mont = $mont([0u64; 4]);
                        $to_mont(&mut mont, &$nonmont(a));
                        let mut prod = $mont([0u64; 4]);
                        $mul(&mut prod, &one, &mont);
                        assert_eq!(prod.0, mont.0, "mul(one, x) must equal x");
                    }
                }

                #[test]
                fn nonzero_semantics() {
                    let mut nz = 0u64;
                    $nonzero(&mut nz, &[0u64; 4]);
                    assert_eq!(nz, 0, "nonzero(0) must be 0");

                    $nonzero(&mut nz, &[1, 0, 0, 0]);
                    assert_ne!(nz, 0, "nonzero(1) must be non-zero");

                    let mut one = $mont([0u64; 4]);
                    $set_one(&mut one);
                    $nonzero(&mut nz, &one.0);
                    assert_ne!(nz, 0, "nonzero(one) must be non-zero");
                }
            }
        };
    }

    self_consistency_tests!(
        bn254fq,
        bn254fq,
        fiat_bn254fq_montgomery_domain_field_element,
        fiat_bn254fq_non_montgomery_domain_field_element,
        fiat_bn254fq_to_montgomery,
        fiat_bn254fq_from_montgomery,
        fiat_bn254fq_mul,
        fiat_bn254fq_set_one,
        fiat_bn254fq_nonzero
    );

    self_consistency_tests!(
        bjjfr,
        bjjfr,
        fiat_bjjfr_montgomery_domain_field_element,
        fiat_bjjfr_non_montgomery_domain_field_element,
        fiat_bjjfr_to_montgomery,
        fiat_bjjfr_from_montgomery,
        fiat_bjjfr_mul,
        fiat_bjjfr_set_one,
        fiat_bjjfr_nonzero
    );
}
