#!/usr/bin/env bash
#
# Regenerate the vendored, formally-verified fiat-crypto constant-time field
# arithmetic in `src/backend/fiat/`.
#
# The output of fiat-crypto is deterministic and independent of the generator's
# host platform, so running this on any OS/arch with the pinned generator
# version reproduces the committed files byte-for-byte (header + lint allowances
# included). Auditors can run this and `git diff` to confirm the vendored code.
#
# Pinned generator: fiat_crypto v0.1.6 (mit-plv/fiat-crypto prebuilt release).
#
# Usage:
#   scripts/gen_fiat.sh                 # auto-download the pinned generator
#   FIAT_CRYPTO=/path/to/fiat_crypto scripts/gen_fiat.sh   # use a local binary
#
set -euo pipefail

FIAT_VERSION="v0.1.6"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${REPO_ROOT}/src/backend/fiat"

# Single cleanup hook for all temp artifacts created below.
_cleanup_paths=()
cleanup() { [ ${#_cleanup_paths[@]} -gt 0 ] && rm -rf "${_cleanup_paths[@]}"; }
trap cleanup EXIT

# BabyJubJub base field Fq == BN254 scalar prime (254-bit).
FQ_PRIME="21888242871839275222246405745257275088548364400416034343698204186575808495617"
# BabyJubJub scalar field Fr == prime-order subgroup order (251-bit).
FR_PRIME="2736030358979909402780800718157159386076813972158567259200215660948447373041"

# Operations to synthesize. `mul square add sub opp` give branch-free, masked
# Montgomery arithmetic; `from_montgomery/to_montgomery` convert domains;
# `nonzero/selectznz` are constant-time helpers; `to_bytes/from_bytes` (de)serialize
# the standard representation; `one/msat/divstep/divstep_precomp` provide the
# Bernstein-Yang constant-time inversion primitives.
OPS=(mul square add sub opp from_montgomery to_montgomery nonzero selectznz \
     to_bytes from_bytes one msat divstep divstep_precomp)

# --- locate or download the pinned generator -------------------------------

fiat_crypto_bin="${FIAT_CRYPTO:-}"
if [ -z "${fiat_crypto_bin}" ]; then
  os="$(uname -s)"
  arch="$(uname -m)"
  case "${os}/${arch}" in
    Darwin/arm64)        asset="Fiat-Cryptography_${FIAT_VERSION}_macOS_arm64";  sha256="a7fc34984f6a82c05227abb2efe622f8c49d6ea95c1d94b7d1daf23034efa6d7" ;;
    Darwin/x86_64)       asset="Fiat-Cryptography_${FIAT_VERSION}_macOS_x86_64"; sha256="" ;;
    Linux/x86_64)        asset="Fiat-Cryptography_${FIAT_VERSION}_Linux_x86_64"; sha256="" ;;
    *) echo "Unsupported host ${os}/${arch}; set FIAT_CRYPTO=/path/to/fiat_crypto" >&2; exit 1 ;;
  esac
  url="https://github.com/mit-plv/fiat-crypto/releases/download/${FIAT_VERSION}/${asset}"
  tmp_dir="$(mktemp -d)"
  _cleanup_paths+=("${tmp_dir}")
  fiat_crypto_bin="${tmp_dir}/fiat_crypto"
  echo "Downloading ${url}" >&2
  curl -sSL -o "${fiat_crypto_bin}" "${url}"
  chmod +x "${fiat_crypto_bin}"
  if [ -n "${sha256}" ]; then
    echo "${sha256}  ${fiat_crypto_bin}" | shasum -a 256 -c - >&2
  else
    echo "WARNING: no pinned sha256 for ${asset}; skipping integrity check." >&2
  fi
fi

# --- generation + post-processing ------------------------------------------

# Prepend the SPDX/provenance header and the extra lint allowances that let the
# generated file pass the crate's strict lints. This mirrors exactly what is in
# the committed files so regeneration is a no-op under `git diff`.
postprocess() {
  local raw="$1" out="$2" field_doc="$3" prime="$4"
  {
    cat <<EOF
// SPDX-License-Identifier: MIT OR Apache-2.0 OR BSD-1-Clause
//
// VENDORED, FORMALLY-VERIFIED code generated by the fiat-crypto project
// (https://github.com/mit-plv/fiat-crypto), distributed under a tri-license of
// MIT, Apache-2.0, and BSD-1-Clause (see the fiat-crypto COPYRIGHT and LICENSE
// files). Reproduced here unmodified except for the added \`#![allow(...)]\` lint
// attributes and this provenance header.
//
// Provenance (regenerate with \`scripts/gen_fiat.sh\`):
//   generator : fiat_crypto ${FIAT_VERSION} (mit-plv/fiat-crypto prebuilt release)
//   strategy  : word-by-word-montgomery, 64-bit limbs
//   field     : ${field_doc}
//               ${prime}
//
// Do not edit by hand.
//
EOF
    # Normalize the generator path in the autogenerated banner, then insert the
    # extra lint allowances right after fiat's own `non_camel_case_types` allow.
    sed -e "1 s#'[^']*fiat_crypto'#'fiat_crypto'#" "${raw}" \
      | awk '
          { print }
          /^#!\[allow\(non_camel_case_types\)\]$/ && !done {
            print "// Extra allowances so this generated file passes the crate'\''s strict lints"
            print "// (`#![deny(warnings, unused, future_incompatible, nonstandard_style,"
            print "// rust_2018_idioms)]`) and `cargo clippy -D warnings`."
            print "#![allow(unused)]"
            print "#![allow(non_snake_case)]"
            print "#![allow(non_upper_case_globals)]"
            print "#![allow(clippy::all)]"
            print "#![allow(clippy::pedantic)]"
            print "#![allow(clippy::nursery)]"
            done = 1
          }
        '
  } > "${out}"
}

mkdir -p "${OUT_DIR}"
raw_fq="$(mktemp)"; raw_fr="$(mktemp)"
_cleanup_paths+=("${raw_fq}" "${raw_fr}")

"${fiat_crypto_bin}" word-by-word-montgomery --lang Rust --inline \
  bn254fq 64 "${FQ_PRIME}" "${OPS[@]}" > "${raw_fq}"
postprocess "${raw_fq}" "${OUT_DIR}/bn254fq.rs" \
  "Fq = BabyJubJub base field = BN254 scalar prime" "${FQ_PRIME}"

"${fiat_crypto_bin}" word-by-word-montgomery --lang Rust --inline \
  bjjfr 64 "${FR_PRIME}" "${OPS[@]}" > "${raw_fr}"
postprocess "${raw_fr}" "${OUT_DIR}/bjjfr.rs" \
  "Fr = BabyJubJub scalar field (prime-order subgroup order)" "${FR_PRIME}"

echo "Regenerated:" >&2
echo "  ${OUT_DIR}/bn254fq.rs" >&2
echo "  ${OUT_DIR}/bjjfr.rs" >&2
